config/routes.rb
Rails.application.routes.draw do


  root 'pages#index'
  resources :chatrooms, path: '/conversations/' do
    resources :messages
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  has_many :messages
  accepts_nested_attributes_for :messages
  validates_associated :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   enum position: {
          users: 0,
          trainer: 1
          }
  has_many :chatrooms
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :position])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :position])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.where(user_id: current_user)
    @inbox = Chatroom.where(reciepient: current_user.id)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
  end
  def new
    @chatroom = Chatroom.new
    @chtroom = @chatroom.messages.new
  end
  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.user_id = current_user.id
    respond_to do |format|
      if @chatroom.save
        # @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
      else
        format.html { render :new }

        end
    end
  end
private

def chatroom_params
  params.require(:chatroom).permit(:name, :user_id, :reciepient, mesages_attributes: [:body, :chatroom_id, :user_id])
end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom
  def create
  message =  @chatroom.messages.new(message_params)
  message.user = current_user
  if message.save
      redirect_to @chatroom
    end
  # MessageRelayJob.perform_later(message)
  end
private
  def set_chatroom
      @chatroom = Chatroom.find(params[:chatroom_id])
  end
  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chatrooms/index.html.erb
<div class="collection">
  <%= link_to "New Chat", new_chatroom_path %>
  <div class="sent">
    <h4>Sent messages</h4>
    <% @chatrooms.each do |chatroom| %>
    <%= link_to chatroom.name, chatroom_path(chatroom.id), class: "collection-item" %>

    <% end %>
  </div>
<div class="inbox">
  <h4>Inbox</h4>
  <% @inbox.each do |chatroom| %>
  <%= link_to chatroom.name, chatroom_path(chatroom.id), class: "collection-item" %>

  <% end %>
</div>
  </div>

app/views/chatrooms/new.html.erb
<%= form_for @chatroom do |f| %>
  <%= render "shared/error_messages", object: @chatroom %>
  <div class="row">

  <div class="input-field col s12">
    <label for="fenter_subject">Enter reciepient</label>
    <div class="">
            <%= f.select :reciepient, User.all - [current_user]).collect { |p| [ p.username, p.id ] } %>
    </div>



  </div>


  <%= f.button "create conversation", class: "waves-effect waves-light btn loginButton" %>

</div>

<% end %>

app/views/chatrooms/show.html.erb
<ul class="collection with-header">
   <li class="collection-header"><h4><%= @chatroom.name %></h4></li>
   <div class="content" data-behavior="messages" data-chatroom-id="<%= @chatroom.id %>" id="content">
<% @messages.each do |message| %>
<%= render message %>

<% end %>
</div>
</ul>
<%= form_for [@chatroom, Message.new] do |f| %>
<%= f.text_field :body, autofocus: :true, class: "main_chat_form"  %>

<button class="btn btn-icon btn-big right">send</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Chat</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
        <li><%= link_to "Log out", main_app.destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Chat", chatrooms_path %></li>
        <% else %>

        <li><%= link_to "Login", new_user_session_path, class: "right waves-effect waves-light btn navbarBtn" %></li>
        <li><%= link_to "Register", new_user_registration_path, class: "right waves-effect waves-light btn navbarBtn" %></li>
<% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div><strong><%= message.user.username %>:</strong> <%= message.body %></div>

app/views/messages/create.js.erb
$("#new_message")[0].reset()

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="notice red darken-4">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li class="notice red"><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>